version: '3.7'

services:
  db_ref:
    image: postgres:10-alpine
    restart: on-failure
    container_name: db_ref
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_REF_DEFAULT_USERNAME} ${DB_REF_DEFAULT_DBNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    ports:
      - 5433:5432
    networks:
      - db

  public_refdata_flyway:
    image: quay.io/ukhomeofficedigital/docker-flyway:9b4c62ed90c599a9bc3282ef06b58818b24762f9
    container_name: public_refdata_flyway
    command: >
      sh -c "/mnt/docker/run.sh &&
             cd /mnt/private-refdata &&
             /mnt/private-refdata/docker/run.sh"
    working_dir: /mnt
    environment:
      DB_REF_DEFAULT_DBNAME: postgres
      DB_REF_DEFAULT_USERNAME: postgres
      DB_REF_DEFAULT_PASSWORD: mysecretpassword
      DB_REF_OPTIONS: ""
      DB_REF_HOSTNAME: db_ref
      DB_REF_PORT: 5432
      DB_REF_REFERENCE_DBNAME: reference
      DB_REF_REFERENCE_SCHEMA: reference
      DB_REF_REFERENCE_OWNER_USERNAME: ownerreference
      DB_REF_REFERENCE_OWNER_PASSWORD: mysecretpassword
      DB_REF_REFERENCE_AUTHENTICATOR_USERNAME: postgres
      DB_REF_REFERENCE_AUTHENTICATOR_PASSWORD: mysecretpassword
      DB_REF_REFERENCE_ANON_USERNAME: webanon
      DB_REF_REFERENCE_SERVICE_USERNAME: servicereference
      DB_REF_REFERENCE_READONLY_USERNAME: refreadonly
      DB_REF_GOVERNANCE_SCHEMA: governance
      DB_REF_GOVERNANCE_OWNER_USERNAME: ownergovernance
      DB_REF_GOVERNANCE_OWNER_PASSWORD: mysecretpassword
      DB_REF_GOVERNANCE_AUTHENTICATOR_USERNAME: authenticatorgovernance
      DB_REF_GOVERNANCE_AUTHENTICATOR_PASSWORD: mysecretpassword
      DB_REF_GOVERNANCE_ANON_USERNAME: webanongovernance
      DB_REF_GOVERNANCE_SERVICE_USERNAME: servicegovernance
      DB_REF_GOVERNANCE_READONLY_USERNAME: readonlygovernance

    volumes:
      - ~/Viable/flyway_ref_public:/mnt
      - ~/Viable/flyway_ref_public:/mnt/private-refdata

    depends_on:
      - db_ref
    networks:
      - db

  ref_data_api:
    container_name: ref_data_api
    build: .
    image: quay.io/ukhomeofficedigital/ref-data-api:dev
    command: npm run start-dev
    volumes:
      - ./app:/src/app
    environment:
      LOG_LEVEL: debug
      PORT: 5001
      DB_CONNECTION_STRING: postgres://authenticatorreference:auth1234@postgres_refdata:5432/reference
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_PUBLIC_KEY: ${KEYCLOAK_CLIENT_PUBLIC_KEY}
      KEYCLOAK_URL: ${KEYCLOAK_URL}
    depends_on:
      - db_ref
      - public_refdata_flyway
    healthcheck:
      test: ["CMD-SHELL", "node", "/src/app/healthcheck.js"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    ports:
     - 5001:5000
    networks:
      - db
      - web

networks:
  db:
    external:
      name: db
  web:
    external:
      name: web
