version: '3.7'

services:
  postgres_refdata:
    image: postgres:10-alpine
    restart: on-failure
    container_name: postgres_refdata
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    ports:
      - 5433:5432
    networks:
      - db

  public_refdata_flyway:
    image: quay.io/ukhomeofficedigital/docker-flyway:0c81630decc5d7f6c6ec9070d7475b3f3f084153
    container_name: public_refdata_flyway
    command: >
      sh -c "/mnt/docker/run.sh &&
             cd /mnt/private-refdata &&
             /mnt/private-refdata/docker/run.sh"
    working_dir: /mnt
    environment:
      POSTGRES_DB: postgres
      POSTGRES_SERVER: postgres_refdata
      POSTGRES_PORT: 5432
      FLYWAY_INIT_USER: postgres
      FLYWAY_INIT_PASSWORD: mysecretpassword
      FLYWAY_PLACEHOLDERS_REFERENCE_DB_NAME: reference
      FLYWAY_PLACEHOLDERS_REFERENCE_OWNER_NAME: ownerreference
      FLYWAY_PLACEHOLDERS_REFERENCE_OWNER_PASSWORD: mysecretpassword
      FLYWAY_PLACEHOLDERS_REFERENCE_SCHEMA: reference
      FLYWAY_PLACEHOLDERS_GOVERNANCE_OWNER_NAME: ownergovernance
      FLYWAY_PLACEHOLDERS_GOVERNANCE_OWNER_PASSWORD: mysecretpassword
      FLYWAY_PLACEHOLDERS_GOVERNANCE_SCHEMA: governance
      FLYWAY_PLACEHOLDERS_REFERENCE_AUTHENTICATOR_USER: authenticatorreference
      FLYWAY_PLACEHOLDERS_REFERENCE_AUTHENTICATOR_PASSWORD: auth1234
      FLYWAY_PLACEHOLDERS_REFERENCE_ANON_USER: webanon
      FLYWAY_PLACEHOLDERS_REFERENCE_SERVICE_USER: servicereference
      FLYWAY_PLACEHOLDERS_REFERENCE_READONLY_USER: refreadonly
      FLYWAY_PLACEHOLDERS_GOVERNANCE_AUTHENTICATOR_USER: authenticatorgovernance
      FLYWAY_PLACEHOLDERS_GOVERNANCE_AUTHENTICATOR_PASSWORD: auth1234
      FLYWAY_PLACEHOLDERS_GOVERNANCE_ANON_USER: webanongovernance
      FLYWAY_PLACEHOLDERS_GOVERNANCE_SERVICE_USER: servicegovernance
      FLYWAY_PLACEHOLDERS_GOVERNANCE_READONLY_USER: readonlygovernance
    volumes:
      - ${PUBLIC_REFDATA_FLYWAY}:/mnt
      - ${PRIVATE_REFDATA_FLYWAY}:/mnt/private-refdata
    depends_on:
      - postgres_refdata
    networks:
      - db

  ref_data_api:
    build: .
    image: quay.io/ukhomeofficedigital/ref-data-api:dev
    command: npm run start-dev
    volumes:
      - ./app:/src/app
    environment:
      LOG_LEVEL: debug
      PORT: 5001
      DB_CONNECTION_STRING: postgres://authenticatorreference:auth1234@postgres_refdata:5432/reference
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_PUBLIC_KEY: ${KEYCLOAK_CLIENT_PUBLIC_KEY}
      KEYCLOAK_URL: ${KEYCLOAK_URL}
    depends_on:
      - postgres_refdata
      - public_refdata_flyway
    healthcheck:
      test: ["CMD-SHELL", "node", "/src/app/healthcheck.js"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    ports:
     - 5001:5001
    networks:
      - db
      - web

networks:
  db:
    external:
      name: db
  web:
    external:
      name: web
