---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{.API_REF_NAME}}
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 33%
      maxSurge: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        name: {{.API_REF_NAME}}
    spec:
      containers:
      - name: api
        image: "{{.API_REF_IMAGE}}:{{.API_REF_TAG}}"
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 500Mi
        livenessProbe:
          exec:
            command:
            - node
            - /src/app/healthcheck.js
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
              - node
              - /src/app/healthcheck.js
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: DB_REF_PROTOCOL
          value: "{{.DB_REF_PROTOCOL}}"
        - name: DB_REF_PORT
          value: "{{.DB_REF_PORT}}"
        - name: DB_REF_HOSTNAME
          value: "{{.DB_REF_HOSTNAME}}"
        - name: DB_REF_OPTIONS
          value: "{{.DB_REF_OPTIONS}}"
        - name: DB_REF_REFERENCE_DBNAME
          value: "{{.DB_REF_REFERENCE_DBNAME}}"
        - name: DB_REF_REFERENCE_SCHEMA
          value: "{{.DB_REF_REFERENCE_SCHEMA}}"
        - name: DB_REF_REFERENCE_AUTHENTICATOR_USERNAME
          value: "{{.DB_REF_REFERENCE_AUTHENTICATOR_USERNAME}}"
        - name: DB_REF_REFERENCE_AUTHENTICATOR_PASSWORD
          value: "{{.DB_REF_REFERENCE_AUTHENTICATOR_PASSWORD}}"
        - name: KEYCLOAK_URL
          value: "{{.KEYCLOAK_URL}}"
        - name: KEYCLOAK_PROTOCOL
          value: "{{.KEYCLOAK_PROTOCOL}}"
        - name: KEYCLOAK_REALM
          value: "{{.KEYCLOAK_REALM}}"
        - name: API_REF_KEYCLOAK_CLIENT_ID
          value: "{{.API_REF_KEYCLOAK_CLIENT_ID}}"
        - name: API_REF_LOG_LEVEL
          value: "{{.API_REF_LOG_LEVEL}}"
        - name: API_REF_PORT
          value: "{{.API_REF_PORT}}"
        ports:
          - name: api
            containerPort: {{.API_REF_PORT}}
      - name: proxy
        image: "{{.NGINX_IMAGE}}:{{.NGINX_TAG}}"
        securityContext:
          runAsNonRoot: true
        env:
          - name: PROXY_SERVICE_HOST
            value: 'http://127.0.0.1'
          - name: PROXY_SERVICE_PORT
            value: "{{.API_REF_PORT}}"
          - name: SERVER_CERT
            value: "/certs/tls.crt"
          - name: SERVER_KEY
            value: "/certs/tls.key"
          - name: LOG_FORMAT_NAME
            value: 'json'
          - name: NAXSI_USE_DEFAULT_RULES
            value: 'FALSE'
          - name: ENABLE_UUID_PARAM
            value: 'FALSE'
        ports:
          - name: https
            containerPort: 10443
        volumeMounts:
          - name: certs
            mountPath: /certs
      volumes:
      - name: certs
        secret:
          secretName: "{{.API_REF_NAME}}-pod-tls"
